### ISSUE TITLE
Module can not be resolved

### ISSUE THREAD

**Issue by ufukbakan** [mindlid/useOnline#2]
Wrong path specified in package json :

  "main": "lib/useOnline.ts",

**Comment by 3xau1o** [comment]
thanks, pushed new version, also removed source files by adding the `files` field

``` json
{
   "main": "lib/useOnline.js",
   "types": "lib/useOnline.d.ts",
   "files": [
      "lib"
   ]
}
```

![image](https://user-images.githubusercontent.com/19735362/205476665-a836b15d-76a0-4577-baed-aa07a3c456ff.png)
